---
- hosts: all
  become: true

  vars: 
    build_root: /vagrant/endpoint
    http_port: "80"
    venv_path: /vagrant/venv

  roles:
    - role: geerlingguy.docker

  tasks:
    - import_tasks: bringup.yml
