# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "bento/ubuntu-24.04"
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end
  
  # uniform config for all VMS
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install -y ansible
  SHELL
   
  # define 3 workers for running container jobs
  #   We cant do arbitrary amounts of workers, since the ansible hosts.ini
  #   directly relies on 3 workers with predictable ips
  config.vm.define "worker1" do |subconfig|
    subconfig.vm.hostname = "worker1.test"
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network "private_network", ip: "192.168.56.11"
    
    subconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/main.yml"
    end
  end
  
  config.vm.define "worker2" do |subconfig|
    subconfig.vm.hostname = "worker2.test"
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network "private_network", ip: "192.168.56.12"
    
    subconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/main.yml"
    end
  end
  
  config.vm.define "worker3" do |subconfig|
    subconfig.vm.hostname = "worker3.test"
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network "private_network", ip: "192.168.56.13"
    
    subconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/main.yml"
    end
  end
  
  config.vm.define "endpoint" do |subconfig|
    subconfig.vm.hostname = "endpoint.test"
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network "private_network", ip: "192.168.56.100"
    
    subconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/main.yml"
      # Caddy Endpoint bringup
      ansible.playbook = "endpoint/main.yml"
    end
  end
end
