# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "bento/debian-12.9"
WORKER_COUNT = 3
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end
    
  # box definitions
  (1..WORKER_COUNT).each do |i|
    config.vm.define "worker#{i}" do |subconfig|
      #subconfig.dns.tld = "test"
      subconfig.vm.hostname = "vagrant#{i}"
      #subconfig.dns.patterns = "worker#{i}.mysite.test"
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.network "private_network", ip: "192.168.56.#{i+10}"
    end
  end
 
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install -y git ansible
  SHELL

  # Use :ansible or :ansible_local to
  # select the provisioner of your choice
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "setup-playbook.yml"
  end


end
