---
- name: Enable docker experimental mode
  ansible.builtin.shell: 'echo {\"experimental\": true} > /etc/docker/daemon.json'
  when: true

- name: Make sure that worked
  ansible.builtin.shell: 'cat /etc/docker/daemon.json | grep "experimental"'

- name: Restart docker daemon
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: docker
