---
- hosts: all
  become: true
 
  vars: 
    build_root: /vagrant/provisioning
    venv_path: /vagrant/venv
  
  roles:    
    - role: python

  tasks:
    - import_tasks: setup.yml
    - import_tasks: podman.yml

# only launch stateful container on worker1
- hosts: worker1
  become: true

  vars: 
    build_root: /vagrant/provisioning
    http_port: "8000"
    venv_path: /vagrant/venv
  
  tasks:
    - import_tasks: bringup.yml

